openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /pets:
    get:
      summary: List all pets
      responses:
        "200":
          description: A paged array of pets
    delete:
      summary: Add new pet
      responses:
        "200":
          description: A paged array of pets
